### ISSUE TITLE
Feedback Sprint 1 Datadashboard

### ISSUE THREAD

**Issue by nerdale** [anameneses/cdmx-2018-06-bc-core-am-data-dashboard#6]
Hola @anameneses y @SofiaQuicheFloresGarcia 

He estado revisando el proyecto y tengo algunos comentarios:

1. En UX/Readme especificamente en el punto **5. User Testing** adjuntan una imagen sobre el flujo del proyecto, ojo con eso, en la data local solo hay información de **Lima, México y Santiago** y veo que en el flujo utilizan **Lima, Sao Paulo, CDMX** y en **Lima** hay información de la **tercera, cuarta y quinta generación**, como consejo, revisen muy bien la data para saber que información tienen disponible y que no.

2. En el link adjunto de Figma, solo veo una pantalla, donde están los sketching de baja y alta fidelidad? 

3. En el archivo html en la línea 26 hay una etiqueta `</optgroup>` que se está cerrando pero no abre en ningún lado, ojo con esos detalles.

4. Recuerden utilizar HTML semántico `<header></header> <section></section> <aside></aside> <footer></footer> <article></article>`

5. Les recomiendo comenzar a trabajar con la data lo antes posible (se encontrarán con toda la lógica para jalar la información y hacer los cálculos) y plasmar tanto visual como funcionalmente lo que tienen pensado para el proyecto.

6. Ojo con el trabajo colaborativo en github, veo 49 commits de @anameneses y solo 2 de @SofiaQuicheFloresGarcia 

Ánimo y en honor al tiempo comiencen luego con a darle forma al datadashboard :rocket: 

--

Alexandra N.-

**Comment by anameneses** [comment]
Gracias @nerdale , el punto #1 ha quedado resuelto.
Se han subido los sketches de baja fidelidad, y se ha obtenido un gran avance en Figma..
Se ha comenzado a trabajar con la data, aun queda mucho por hacer....
